# yaml-language-server: $schema=json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
version: 3
ignore_actions:
  - name: actions/setup-java
    name_format: fixed_string
    ref: v3
    ref_format: fixed_string
  - name: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
    name_format: fixed_string
  - name: "^peaceiris/"
    name_format: regexp
