# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/v1.3.0/json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
files:
  - pattern: "^\\.github/workflows/.*\\.ya?ml$"
  - pattern: "^(.*/)?action\\.ya?ml$"
  - pattern: "^testdata/.*\\.ya?ml$"

ignore_actions:
  - name: actions/setup-java
  - name: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
  - name: "^peaceiris/"
