---
- id: pinact
  name: Pin versions of Actions and reusable workflows
  description: Pin versions of GitHub Actions and reusable workflows
  entry: pinact run --verify-comment
  language: golang
  types: [yaml]
  files: ^(\.github/workflows/[^/]+|([^/]+/){0,3}action)\.ya?ml$

- id: pinact-update
  name: Pin and update versions of Actions and reusable workflows
  description: Pin and update versions of GitHub Actions and reusable workflows
  entry: pinact run --verify-comment --update
  language: golang
  types: [yaml]
  files: ^(\.github/workflows/[^/]+|([^/]+/){0,3}action)\.ya?ml$

- id: pinact-check
  name: Validate versions of Actions and reusable workflows
  description: Validate versions of GitHub Actions and reusable workflows
  entry: pinact run --verify-comment --check
  language: golang
  types: [yaml]
  files: ^(\.github/workflows/[^/]+|([^/]+/){0,3}action)\.ya?ml$

- id: pinact-system
  name: Pin versions of Actions and reusable workflows
  description: Pin versions of GitHub Actions and reusable workflows
  entry: pinact run --verify-comment
  language: system
  types: [yaml]
  files: ^(\.github/workflows/[^/]+|([^/]+/){0,3}action)\.ya?ml$
