// Package schema embeds the JSON Schema of the configuration file so that
// 'pinact json-schema' can output it. The file is generated by
// 'go run ./cmd/gen-jsonschema' (cmdx js) and committed, so it is also served from
// GitHub for editors that refer to it by URL.
package schema

import (
	_ "embed"
)

// Schema is the content of json-schema/pinact.json.
//
//go:embed pinact.json
var Schema []byte
