package schema_test

import (
	"encoding/json"
	"testing"

	schema "github.com/suzuki-shunsuke/pinact/v5/json-schema"
)

// TestSchema checks that the embedded file is a JSON Schema, so that both
// `pinact json-schema > pinact.json` and the editors reading json-schema/pinact.json
// from GitHub get something they can use. The file is generated by
// 'go run ./cmd/gen-jsonschema' and committed, so nothing else checks it.
func TestSchema(t *testing.T) {
	t.Parallel()
	m := map[string]any{}
	if err := json.Unmarshal(schema.Schema, &m); err != nil {
		t.Fatalf("the schema isn't a JSON object: %v", err)
	}
	if _, ok := m["$schema"]; !ok {
		t.Error("the schema has no $schema")
	}
}
